---
title: "EDA for SFCS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(dplyr)
library(ggplot2)
library(lubridate)
library(scales)
library(tidyr)
```

## Load data

In initial_exploration_sfcs.Rmd we did some data prep work and saved updated versions of the data.

```{r load_data}
load("sfcs_prepped.Rdata")
```

```{r}
str(trip)
```

```{r}
summary(trip)
```


## EDA of trip duration

Some of these were also done in the initial_exploration_sfcs.Rmd file.

```{r}
summary(trip$duration)
```

```{r}
print(quantile(trip$duration, 0.98))
print(quantile(trip$duration, 0.99))
print(quantile(trip$duration, 0.999))
```

```{r}
mean(trip$duration < 7200)
```

```{r fig.width = 8, fig.height = 6}
trip %>% 
  filter(duration < 7200) %>% 
  ggplot() + geom_histogram(aes(x = duration, y = ..density..), binwidth = 60) +
  coord_cartesian(xlim = c(0, 7500))
```

```{r fig.width = 12, fig.height = 10}
trip %>% 
  filter(duration < 7200) %>% 
  ggplot() + geom_histogram(aes(x = duration, y = ..density.., fill = round_trip), binwidth = 60) +
  facet_grid(subscription_type ~ round_trip) +
  coord_cartesian(xlim = c(0, 7500))
```

```{r fig.width = 8, fig.height = 6}
trip %>% 
  filter(duration < 7200) %>% 
  ggplot() + stat_ecdf(aes(x = duration), geom = "step") +
  facet_grid(subscription_type ~ round_trip) +
  coord_cartesian(xlim = c(0, 7500))
```

```{r}
trip %>% 
  filter(duration < 7200) %>%
  ggplot(aes(duration)) + stat_ecdf(geom = "step")
```


```{r fig.width = 8, fig.height = 6}
trip %>% 
  filter(duration < 86400) %>% 
  ggplot() + geom_boxplot(aes(x = subscription_type, y = duration)) +
  coord_cartesian(ylim = c(0, 7500))
```

Vast majority of trips are subscribers.

```{r fig.width = 8, fig.height = 6}
trip %>% 
  filter(duration < 86400, subscription_type == "Subscriber") %>% 
  ggplot() + geom_boxplot(aes(x = round_trip, y = duration)) +
  coord_cartesian(ylim = c(0, 25000))
```


### Station level duration analaysis

Let's try to do the 2x2 histograms for the top 10 stations in terms of volume.

```{r station_histos, fig.height=16, fig.width=12}
top10starts <- trip %>% 
  group_by(start_station_name) %>% 
  summarize(
    num_trips = n()
  ) %>% 
  arrange(desc(num_trips)) %>% head(10)

trip %>% 
  filter(duration < 7200, start_station_name %in% top10starts$start_station_name) %>% 
  ggplot() + geom_histogram(aes(x = duration, y = ..density.., fill = round_trip), alpha=0.7, position="identity", binwidth = 60) +
  facet_wrap(~start_station_name) +
  coord_cartesian(xlim = c(0, 7500))
```

```{r station_histo2, fig.height=16, fig.width=12}
trip %>% 
  filter(duration < 7200, start_station_name %in% top10starts$start_station_name) %>% 
  ggplot() + geom_histogram(aes(x = duration, y = ..density.., fill = round_trip), alpha=0.7, position="identity", binwidth = 60) +
  facet_grid(start_station_name ~ subscription_type) +
  coord_cartesian(xlim = c(0, 7500))
```

```{r station_histo3, fig.height=16, fig.width=12}
trip %>% 
  filter(duration < 7200, start_station_name %in% top10starts$start_station_name) %>% 
  ggplot() + geom_histogram(aes(x = duration, fill = round_trip), alpha=0.7, position="identity", binwidth = 60) +
  facet_grid(start_station_name ~ subscription_type) +
  coord_cartesian(xlim = c(0, 7500))
```

```{r station_histos4, fig.height=16, fig.width=12}
top25starts_subscriber <- trip %>% 
  filter(subscription_type == "Subscriber") %>% 
  group_by(start_station_name) %>% 
  summarize(
    num_trips = n()
  ) %>% 
  arrange(desc(num_trips)) %>% head(25)

trip %>% 
  filter(duration < 7200, start_station_name %in% top25starts_subscriber$start_station_name) %>% 
  ggplot() + geom_histogram(aes(x = duration, fill = round_trip), alpha=0.7, position="identity", binwidth = 60) +
  facet_wrap(~start_station_name) +
  coord_cartesian(xlim = c(0, 7500))
```

```{r top25station_box, fig.width=12}
trip %>% 
  filter(duration < 7200, start_station_name %in% top25starts_subscriber$start_station_name) %>% 
  ggplot() + geom_boxplot(aes(x = start_station_name, y = duration)) + coord_flip()
```

